---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=runn
install: 
  - sudo apt update
  - sudo apt install -y mesa-opencl-icd libpcap-dev clinfo
  - clinfo
  - locate libOpenCL
  - source ~/.cargo/env || true
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - cargo test
  - cargo build --release
sudo: required
