---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=runn
install: 
  - sudo apt update
  - sudo apt install -y ocl-icd-opencl-dev clinfo
  - clinfo
  - git clone https://github.com/pocl/pocl
  - cd pocl
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - clinfo
  - source ~/.cargo/env || true
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - cargo test
  - cargo run
  - cargo run --release
sudo: required
